"""Portfolio accounting.

A :class:`Portfolio` tracks a set of :class:`Position` objects plus a cash
balance, and knows how to compute total market value and P&L given a mark.
It is deliberately low-level: strategies rarely touch it directly. Engine
bridges use it to translate a weights panel into position fills.

Design notes
------------
* Positions are keyed by instrument symbol (not by ``Instrument`` itself)
  to keep lookup cheap and serialisation simple.
* ``Portfolio`` is mutable by design — backtests need to evolve state
  over time. Snapshotting is the caller's responsibility.
* ``rebalance_to_weights`` is the single rebalance entrypoint: every
  strategy-driven trade ultimately flows through it.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from collections.abc import Mapping


@dataclass
class Position:
    """A single position in one instrument.

    We use ``dataclass`` (not pydantic) here because positions mutate on
    every fill and pydantic ``frozen=True`` would force reallocation per
    tick — a real bottleneck in backtests with thousands of instruments.
    """

    symbol: str
    quantity: float = 0.0
    avg_cost: float = 0.0
    last_price: float = 0.0

    @property
    def market_value(self) -> float:
        """Mark-to-market value at ``last_price``."""
        return self.quantity * self.last_price

    @property
    def unrealized_pnl(self) -> float:
        """Unrealised P&L vs. ``avg_cost``."""
        return (self.last_price - self.avg_cost) * self.quantity

    def apply_fill(self, quantity_delta: float, fill_price: float) -> float:
        """Apply a fill and return the realised P&L (zero if no close).

        Parameters
        ----------
        quantity_delta
            Signed quantity change. Positive = buy, negative = sell.
        fill_price
            Execution price.

        Returns
        -------
        realised_pnl
            Realised P&L generated by this fill. Non-zero only when the
            fill partially or fully closes an existing position.
        """
        if not math.isfinite(quantity_delta) or not math.isfinite(fill_price):
            raise ValueError("quantity_delta and fill_price must be finite")
        if fill_price < 0:
            raise ValueError(f"fill_price must be non-negative, got {fill_price}")

        realised: float = 0.0
        new_qty = self.quantity + quantity_delta

        # Same-direction add: weighted-average the cost basis.
        if self.quantity == 0 or (self.quantity > 0) == (quantity_delta > 0):
            total_cost = self.avg_cost * self.quantity + fill_price * quantity_delta
            self.avg_cost = total_cost / new_qty if new_qty != 0 else 0.0
        else:
            # Opposite direction: realise P&L on the closed portion.
            closed_qty = min(abs(self.quantity), abs(quantity_delta))
            sign = 1.0 if self.quantity > 0 else -1.0
            realised = sign * closed_qty * (fill_price - self.avg_cost)
            # If we flipped past zero, new avg_cost is the fill price of
            # the residual.
            if abs(quantity_delta) > abs(self.quantity):
                self.avg_cost = fill_price
            elif new_qty == 0:
                self.avg_cost = 0.0
            # else: avg_cost unchanged on partial close.

        self.quantity = new_qty
        self.last_price = fill_price
        return realised


@dataclass
class Portfolio:
    """A bag of :class:`Position` objects plus cash.

    This class is consumed by every engine bridge. It knows:
    * how to value itself given current prices,
    * how to rebalance to a set of target weights,
    * how to apply fills.
    """

    cash: float = 100_000.0
    base_currency: str = "USD"
    positions: dict[str, Position] = field(default_factory=dict)
    realised_pnl: float = 0.0

    # ------------------------------------------------------------------
    # Valuation
    # ------------------------------------------------------------------
    def mark(self, prices: Mapping[str, float]) -> None:
        """Update every position's ``last_price`` from a price map."""
        for symbol, position in self.positions.items():
            price = prices.get(symbol)
            if price is not None and math.isfinite(price):
                position.last_price = price

    def total_value(self) -> float:
        """Cash + mark-to-market value of every open position."""
        return self.cash + sum(p.market_value for p in self.positions.values())

    def weights(self) -> dict[str, float]:
        """Current position weights relative to total portfolio value."""
        total = self.total_value()
        if total <= 0:
            return {}
        return {
            symbol: p.market_value / total
            for symbol, p in self.positions.items()
            if p.quantity != 0
        }

    # ------------------------------------------------------------------
    # Trading
    # ------------------------------------------------------------------
    def get_or_create(self, symbol: str) -> Position:
        """Return the position for ``symbol``, creating one if missing."""
        if symbol not in self.positions:
            self.positions[symbol] = Position(symbol=symbol)
        return self.positions[symbol]

    def apply_fill(
        self,
        symbol: str,
        quantity_delta: float,
        fill_price: float,
        commission: float = 0.0,
    ) -> None:
        """Apply a single fill, updating cash, position, and realised P&L."""
        if not math.isfinite(commission) or commission < 0:
            raise ValueError(f"commission must be non-negative and finite, got {commission}")
        position = self.get_or_create(symbol)
        realised = position.apply_fill(quantity_delta, fill_price)
        self.cash -= quantity_delta * fill_price
        self.cash -= commission
        self.realised_pnl += realised

    def rebalance_to_weights(
        self,
        target_weights: Mapping[str, float],
        prices: Mapping[str, float],
        commission_bps: float = 0.0,
    ) -> None:
        """Trade the portfolio to hit ``target_weights`` given ``prices``.

        Weights are fractions of *total portfolio value* (cash + positions).
        Any symbol present in current positions but missing from
        ``target_weights`` is closed.
        """
        if commission_bps < 0:
            raise ValueError(f"commission_bps must be non-negative, got {commission_bps}")

        self.mark(prices)
        total = self.total_value()
        if total <= 0:
            raise ValueError(f"cannot rebalance zero/negative equity portfolio (total={total})")

        # First close anything not in the target set.
        for symbol in list(self.positions):
            if symbol not in target_weights and self.positions[symbol].quantity != 0:
                price = prices.get(symbol)
                if price is None:
                    continue
                qty = self.positions[symbol].quantity
                commission = abs(qty) * price * commission_bps / 10_000
                self.apply_fill(symbol, -qty, price, commission=commission)

        # Then rebalance each target to the correct size.
        for symbol, target_weight in target_weights.items():
            if not math.isfinite(target_weight):
                raise ValueError(f"target_weight for {symbol} must be finite")
            price = prices.get(symbol)
            if price is None or price <= 0:
                continue
            current_qty = self.positions.get(symbol, Position(symbol=symbol)).quantity
            target_qty = target_weight * total / price
            delta = target_qty - current_qty
            if abs(delta * price) < 1e-6:  # ignore dust trades
                continue
            commission = abs(delta) * price * commission_bps / 10_000
            self.apply_fill(symbol, delta, price, commission=commission)
